### ISSUE TITLE
I often have to reload the page for appmode to work

### ISSUE THREAD

**Issue by choldgraf** [oschuett/appmode#19] opened 2018-08-09 00:58 UTC
I'm not sure why, but many times when I click a Binder link that points to an appmode page, the page seems to load and then hangs. If I ctrl+r reload the page, then it loads just fine. Has anyone else experienced anything like this?

**Comment by oschuett** [comment] 2018-08-20 16:06
Sorry, for the late reply. I have not encountered this problem before. Does your Javascript console show the message "_Appmode: initialization finished"_ ?

**Comment by choldgraf** [comment] 2018-08-20 16:44
no worries - I'll return here if I find another repo that replicates this. It's something I've seen off and on and just wanted to post it here in case it was something others had seen

**Comment by kmader** [comment] 2018-08-22 18:16
I found this sometimes happens if the tab is in the background on Chrome.

**Comment by oschuett** [comment] 2018-08-23 10:36
I'm sorry, I can't reproduce it.

Appmode is initialized in multiple steps, which are triggered by the server via events like ```kernel_ready.Kernel```. So the most likely reason is that one of those events gets lost, e.g due to some timeout as the background tab is starved.

If you want to pursuit this further, you could add some more logging to figure out which event gets lost. Then you could file this as an issue with the Jupyter project.

**Comment by oschuett** [comment] 2018-10-19 20:43
I'm closing this issue for now. Feel free to re-open if there are any news.

**Closed by oschuett** 2018-10-19 20:43 UTC

**Comment by oschuett** [comment] 2019-01-22 16:19
This was likely fixed by @parente via #28.

**Comment by MartijnZ** [comment] 2020-05-18 11:28
Hi,

I've recently tried Appmode for Jupyter. I really like it, as it provides an easy way to create web-based interfaces without troubling people with code!

I'm running the service on a remote server, and found a similar issue raised by @choldgraf. I sometimes need to reload the page in order to get the appmode running. Otherwise, the 'loading page' keeps displaying forever. 

I'm currently using the latest version (0.7.0), so I'm guessing it might not be related to the 'racing-condition' mentioned earlier. Are there any other suggestions?

Cheers,

Martijn
