### ISSUE TITLE
Interest in server side options for trusted path, hiding buttons, etc.?

### ISSUE THREAD

**Issue by parente** [oschuett/appmode#27] opened 2019-01-16 21:51 UTC
I'm currently working on adding some traitlets to appmode. My goal is to allow admins of jupyterhub instances the ability to configure features of appmode from the standard jupyter command line and config files (e.g., `jupyter notebook --AppmodeManager.trusted_path='only/apps/here/can/launch/in/appmode'`).  

Instead of sending a drive by PR that expands the project scope, I wanted to check to see if you have any interest. No worries if not--I can easily make do with my own fork.

PS - Thanks for creating appmode.

**Comment by oschuett** [comment] 2019-01-17 20:33
Hi Peter, I'm happy to include your changes. Just a few remarks:
- For the sake of other users, the current behavior must not change with the default settings.
- Maybe `Appmode` is a better name than `AppmodeManager`? It would make the command line look nicer.
- Are you aware of the [Jupyter trust model](https://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-notebook-documents)? Maybe we should follow their lead and add sth. like `--Appmode.run_only_trusted`. Then again, I don't know your use-case.

**Comment by parente** [comment] 2019-01-17 22:22
Thanks @oschuett. 

> For the sake of other users, the current behavior must not change with the default settings.

Absolutely. The defaults will remain the same.

> Maybe Appmode is a better name than AppmodeManager? It would make the command line look nicer.

Agreed. The `AppmodeManager` was an attempt to mirror the existing notebook classes that allow traitlet configuration (ContentsManager, KernelManager, etc.) I'm fine with shortening.

> Are you aware of the Jupyter trust model? Maybe we should follow their lead and add sth. like --Appmode.run_only_trusted. Then again, I don't know your use-case.

I am. I think that's a reasonable option to support. In my use case, however, it does not work. I'm looking to have notebooks not writable by the local user deployed to a standard location after code review, testing, etc. In that situation, the trust is established external to jupyter, and there's no way for the user's notebook server to stamp the notebook as "trusted" before entering app mode.

"Why not both?" is my gut reaction. I don't think it would bloat the code very much and we can add them incrementally along with documentation about when to use either.

I'll send a PR soonish. I'm fighting with an interesting, unrelated race condition where the widgets vanish after displaying briefly on the appmode page. I'll see if I can fix that too.

**Comment by oschuett** [comment] 2019-01-21 16:58
Sorry for the long silence. It's great that you managed to nail that race condition! People have been reporting it, but I was never able to reproduce it.

Your PRs look good. Unfortunately, I was a bit buys today. I'll test and merge them this week. Afterwards I'll make a new release.

**Comment by oschuett** [comment] 2019-01-22 16:44
> Clearing all outputs makes the notebook implicitly trusted.

Oh, I didn't know that.

Nevertheless, I'm still not sure about your approach.

> I'm looking to have notebooks that are read-only to users deployed to a standard location...

I don't think this will work, because Appmode creates [temporary copies](https://github.com/oschuett/appmode/blob/master/appmode/server_extension.py#L74) of the notebook.

In general Juypter is very insecure by design. AFAIK, the only save way to serve notebooks publicly is via JupyterHub, ie. like MyBinder does.

What kind of attack are you actually trying to mitigate? Maybe `--notebook-dir` is sufficient?

For hiding buttons I usually point people to [custom.js](https://github.com/oschuett/appmode#customization). Couldn't that also work for you?

I'm sorry for these late objections. I just want to make sure that we're not missing anything.

I do like how  you moved the button to the side. It looks much better now.

**Comment by parente** [comment] 2019-01-22 17:42
> I don't think this will work, because Appmode creates temporary copies of the notebook.

In our setup, we have a "clone" facility that let's users grab a peer-reviewed notebook from a central location. For notebooks identified in our system as "apps", we copy them to a specific `.appmode` subfolder under the user's notebook dir. We then redirect to `/user/p-someone/appmode/.appmode/the_notebook.ipynb` which causes appmode to make a temp copy of the notebook in that same directory, launch its kernel, run all cells, etc.

If a bad actor (or more likely, unaware user) visits a link that leads them to`/user/p-someone/appmode/some_other_notebook.ipynb`, the new setting prevents that notebook from immediately launching, hiding all code, and running all cells. In our setup at least, only notebooks that come from our trusted repo, are identified as apps, and follow our cloning process wind up in the `.appmode` folder and can Run All in app mode with a single (accidental?) link click.

If you think the `trusted_path` option and its use is too specific to our setup, it's fine if we run from a fork.

**Comment by oschuett** [comment] 2019-01-23 19:49
Ok, I see you thought this through :-)
I just merged your PR. Unless there is anything else you want to add, I'll update the Readme and make a release within the next days.

**Comment by oschuett** [comment] 2019-01-25 14:38
Ok, Appmode 0.5.0 is out. Thanks again.

**Closed by oschuett** 2019-01-25 14:38 UTC
