### ISSUE TITLE
Appmode button not appearing

### ISSUE THREAD

**Issue by outlace** [oschuett/appmode#5] opened 2017-12-20 20:21 UTC
I installed using conda on Mac OSX 10.12.6 in a conda environment but after restarting the jupyter server the appmode button does not appear. I have the nbextensions configuration tool installed and appmode shows up in the list of nbextensions. I also have jupyter dashboard installed, does it conflict with that?  I also tried on a Windows machine and it doesn't show up there either.

**Comment by oschuett** [comment] 2017-12-21 22:35
Thanks for reporting. Yes, it is very likely that the dashboard extension somehow interferes with Appmode. I'll have a deeper look after the holidays.

**Comment by oschuett** [comment] 2018-03-15 19:59
Sorry, I didn't get back to this in time. I hope you found a solution? Otherwise please reopen the issue.

**Comment by djsegal** [comment] 2018-03-28 21:52
just happened to me too. no solution in sight. :(

until then, ill be testing in prod with binder

**Comment by oschuett** [comment] 2018-03-29 16:44
So, I finally had a closer look. Unfortunately, I was not able to reproduce your problem. For me Appmode and Jupyter-Dashboards work together seamlessly.

You can reproduce my setup from the Dockerfile below:
1. Save it in some directory as `Dockerfile`
2. Goto that directory
3. Run `docker build --tag demo .`
4. Run `docker run --init -ti -p8888:8888 demo`
5. Open `localhost:8888/apps/dashboards/etc/notebooks/got_scotch_demo/scotch_dashboard.ipynb?dashboard=1`

```
FROM ubuntu:rolling
USER root

# Install some Debian package
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-setuptools     \
    python3-wheel          \
    python3-pip            \
    git                    \
  && rm -rf /var/lib/apt/lists/*

# install Python pages
RUN pip3 install notebook ipywidgets appmode jupyter-dashboards          && \
    jupyter nbextension     enable --py --sys-prefix widgetsnbextension  && \
    jupyter nbextension     enable --py --sys-prefix appmode             && \
    jupyter serverextension enable --py --sys-prefix appmode             && \
    jupyter dashboards quick-setup --sys-prefix


# download examples
RUN git clone https://github.com/jupyter/dashboards.git
RUN pip3 install -r dashboards/requirements-demo.txt

# Launch Notebook server
EXPOSE 8888
CMD ["jupyter-notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''"]
```

**Comment by oschuett** [comment] 2018-03-29 20:45
I just realized that the Mac OSX and Windows packages are missing from conda-forge. So, this is probably not related to the dashboards but instead a duplicate of  #10.

**Comment by djsegal** [comment] 2018-03-29 21:24
Probably right. How I got it to work was use:

```
pip install appmode
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
```

// because `conda install --channel conda-forge appmode` didn't work

**Comment by oschuett** [comment] 2018-03-30 16:43
I re-rendered the conda-forge feedstock. Now there are appmode-0.2.0 packages for all architectures. Could you give them a try?

**Closed** 2018-03-31 21:10 UTC

**Comment by Emaasit** [comment] 2018-04-12 01:04
@oschuett I tried both options using pip and conda but I still get the message below. Please help.

<img width="812" alt="screen shot 2018-04-11 at 9 03 33 pm" src="https://user-images.githubusercontent.com/7738216/38650807-dc34de36-3dcb-11e8-897b-bdeef5374e52.png">

**Comment by Emaasit** [comment] 2018-04-12 01:11
Sorry, It worked. I had to stop and start my docker container,

**Comment by Jakolien** [comment] 2021-01-28 09:46
It is still not working for me on windows 10. I tried installing it both with pip and conda, but no button appears. I see the app in nb extensions on jupyter notebook, but it gives me the following message: "This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it."  I put the environment.yml file in my local repository though. Any thoughts on how to solve this?

**Comment by oschuett** [comment] 2021-01-28 10:21
Appmode does not provide a yaml file for [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator), because its nbextension has no config options.

The only thing you need to do is to enable both the nbextension **and** the server extension via:
```
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
```
